### ISSUE TITLE
dwl fails to compile with GCC 12.2.0

### ISSUE THREAD

**Issue by HanoJing** [djpohly/dwl#303]
## Info
dwl's commit: 9bcef3d
wlroots version: 0.15.1
## Description

dwl fails to compile with GCC version: 12.2.0
Log: https://0x0.st/oflH.txt

dwl succeeds to compile with GCC version: 10.2.1pre1

Many thanks, awesome project!

**Comment by sevz17** [comment]
The log you sent is from wlroots git

**Comment by HanoJing** [comment]
Ah, that makes sense, I'm on Gentoo where wlroots is really new. 

Does the CPU architecture matter by any chance?

```
c99 dwl.o util.o `pkg-config --libs wlroots wayland-server xkbcommon libinput xcb`   `pkg-config --cflags wlroots wayland-server xkbcommon libinput xcb` -I. -DWLR_USE_UNSTABLE -DVERSION=\"`git describe --long --tags --dirty 2>/dev/null || echo 0.3.1`\" -O1 -DXWAYLAND -o dwl
/usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: undefined reference to symbol 'xcb_icccm_wm_hints_get_urgency'
/usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: /usr/lib64/libxcb-icccm.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:25: dwl] Error 1 
```

**Comment by sevz17** [comment]
> Ah, that makes sense, I'm on Gentoo where wlroots is really new.
> 
> Does the CPU architecture matter by any chance?
> 
> ```
> c99 dwl.o util.o `pkg-config --libs wlroots wayland-server xkbcommon libinput xcb`   `pkg-config --cflags wlroots wayland-server xkbcommon libinput xcb` -I. -DWLR_USE_UNSTABLE -DVERSION=\"`git describe --long --tags --dirty 2>/dev/null || echo 0.3.1`\" -O1 -DXWAYLAND -o dwl
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: undefined reference to symbol 'xcb_icccm_wm_hints_get_urgency'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: /usr/lib64/libxcb-icccm.so.4: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:25: dwl] Error 1 
> ```
> 

In this case append xcb-icccm into XLIBS

> When compiling without `XLIBS` `XWAYLAND`:
> 
> ```
> c99 dwl.o util.o `pkg-config --libs wlroots wayland-server xkbcommon libinput `  -Wl,--copy-dt-needed-entries `pkg-config --cflags wlroots wayland-server xkbcommon libinput ` -I. -DWLR_USE_UNSTABLE -DVERSION=\"`git describe --long --tags --dirty 2>/dev/null || echo 0.3.1`\" -O1  -o dwl
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `resize':
> dwl.c:(.text+0x7ec): undefined reference to `wlr_xdg_toplevel_set_bounds'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `xytonode':
> dwl.c:(.text+0xab4): undefined reference to `wlr_scene_buffer_from_node'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.c:(.text+0xab8): undefined reference to `wlr_scene_surface_from_buffer'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `cleanupkeyboard':
> dwl.c:(.text+0xdc0): undefined reference to `wlr_keyboard_from_input_device'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `inputdevice':
> dwl.c:(.text+0x122c): undefined reference to `wlr_keyboard_from_input_device'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.c:(.text+0x123c): undefined reference to `wlr_pointer_from_input_device'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `arrangelayer':
> dwl.c:(.text+0x1768): undefined reference to `wlr_scene_layer_surface_v1_configure'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `createlayersurface':
> dwl.c:(.text+0x3898): undefined reference to `wlr_scene_layer_surface_v1_create'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `main':
> dwl.c:(.text+0x4368): undefined reference to `wlr_single_pixel_buffer_manager_v1_create'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.c:(.text+0x4370): undefined reference to `wlr_subcompositor_create'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:25: dwl] Error 1
> ```

Tomorrow I'll check this

**Comment by HanoJing** [comment]
Thanks, appending xcb-icccm fixed the `DSO missing from command line` error but the latter persists.
Thanks so far though.

**Comment by sevz17** [comment]
> When compiling without `XLIBS` `XWAYLAND`:
> 
> ```
> c99 dwl.o util.o `pkg-config --libs wlroots wayland-server xkbcommon libinput `  -Wl,--copy-dt-needed-entries `pkg-config --cflags wlroots wayland-server xkbcommon libinput ` -I. -DWLR_USE_UNSTABLE -DVERSION=\"`git describe --long --tags --dirty 2>/dev/null || echo 0.3.1`\" -O1  -o dwl
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `resize':
> dwl.c:(.text+0x7ec): undefined reference to `wlr_xdg_toplevel_set_bounds'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `xytonode':
> dwl.c:(.text+0xab4): undefined reference to `wlr_scene_buffer_from_node'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.c:(.text+0xab8): undefined reference to `wlr_scene_surface_from_buffer'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `cleanupkeyboard':
> dwl.c:(.text+0xdc0): undefined reference to `wlr_keyboard_from_input_device'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `inputdevice':
> dwl.c:(.text+0x122c): undefined reference to `wlr_keyboard_from_input_device'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.c:(.text+0x123c): undefined reference to `wlr_pointer_from_input_device'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `arrangelayer':
> dwl.c:(.text+0x1768): undefined reference to `wlr_scene_layer_surface_v1_configure'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `createlayersurface':
> dwl.c:(.text+0x3898): undefined reference to `wlr_scene_layer_surface_v1_create'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.o: in function `main':
> dwl.c:(.text+0x4368): undefined reference to `wlr_single_pixel_buffer_manager_v1_create'
> /usr/lib/gcc/aarch64-unknown-linux-gnu/12.2.0/../../../../aarch64-unknown-linux-gnu/bin/ld: dwl.c:(.text+0x4370): undefined reference to `wlr_subcompositor_create'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:25: dwl] Error 1
> ```

What version of wlroots is this?

**Comment by HanoJing** [comment]
0.15.1

**Comment by sevz17** [comment]
Mmm, compile main branch with wlroots-0.15.x and wlroots-next branch with wlroots-git

**Comment by HanoJing** [comment]
compiling main branch with wlroots-0.15.x succeeds.
compiling wlroots-next branch with wlroots-git fails.
Thanks for your help and efforts! The first compile succeeds which is good enough for me.
